# Generated by Django 2.1.4 on 2018-12-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='area',
        ),
        migrations.AddField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.food'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ordered_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='ordered_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tell',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='viwed_num',
            field=models.IntegerField(default=0),
        ),
    ]
